# Generated by Django 5.2.4 on 2025-12-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0002_document_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="group",
            new_name="section",
        ),
    ]
